# fly.toml app configuration file generated for label-assay on 2026-07-14T23:14:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'label-assay'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
